### ISSUE TITLE
Monster AI system

### ISSUE THREAD

**Issue by JadenBalogh** [ubco-video-game-development-club/rpg#14]

**Comment by LoganParker** [comment]
Has this been done by @JonathanQ-Maker ? I believe he pushed some enemy pathfinding a little while ago. If not, I'd be keen to start on this

**Comment by JadenBalogh** [comment]
> Has this been done by @JonathanQ-Maker ? I believe he pushed some enemy pathfinding a little while ago. If not, I'd be keen to start on this - #21 ?

@JonathanQ-Maker does have a PR open (currently with changes requested) which is for pathfinding in general, so is related to this issue but does not resolve it completely. Similarly, @TheArchitect4855 has created a behaviour tree system which can also be applied to the enemy AI issue, and this is merged into `dev`.

I'd be interested to hear from those two to see if they have any further insight on this, but I think it would totally be cool if you took on the rest of this task. The remaining work would basically be creating one or more behaviours through Arch's system that would do proper pathfinding (using Jonathan's work) to make a usable AI behaviour tree. Arch has already made an example random agent behaviour tree that would be a great example to follow. Down to discuss more in Discord.

**Comment by TheArchitect4855** [comment]
I think finishing this task would be integrating all of the basic behaviour tree nodes for everyone to use. @LoganParker , if you want to take this on go for it. I'll try to make some docs for the behaviour tree as well.

**Comment by JadenBalogh** [comment]
I'm assigning myself to this task. After reviewing the current A* pathfinding progress, I believe the amount of time needed to get it integrated with Unity tilemaps and our behaviour tree system is not worth it for the first milestone. I'm going to build some basic AI behaviours that don't use actual pathfinding for now, so we can focus our time on level building rather than these systems.
