### ISSUE TITLE
Add Zoom Out/In functionality to the dialogue graphs.

### ISSUE THREAD

**Issue by wubbadukky** [ubco-video-game-development-club/rpg#59]
I can't fit alot of dialogue nodes in one graph just based on window room so I think zooming out would be helpful. Not a big deal though.

**Comment by TheArchitect4855** [comment]
This is surprisingly broken. Scaling the Unity GUI makes things just *not render* sometimes, so this'll take a good bit of hacking...

**Comment by JadenBalogh** [comment]
Understood. Also, it's worth noting this issue was created before @wubbadukky realized you could pan the dialogue window, so he thought the usable space was limited. I would call this a pretty low-priority issue atm.

**Comment by TheArchitect4855** [comment]
Roger roger

**Comment by JadenBalogh** [comment]
Closing this as I don't think this will be a necessary feature at any point for the reasons outlined above.
