### ISSUE TITLE
Simplify / clarify the dialogue tree text entry interface

### ISSUE THREAD

**Issue by JadenBalogh** [ubco-video-game-development-club/rpg#62]
The dialogue trees aren't super clear between which text area is meant for NPC text and which is meant for Player text. We should at the very least update those labels to indicate "NPC" and "Player" specifically, but it may be worth looking into other options to clarify this interface as well. NOTE: Ensure that existing data doesn't get wiped when this change is made!

**Comment by wubbadukky** [comment]
We also might want to consider how the nodes get names. I say this because if we have long stints of dialogue from one charcter where the player just has to hit e.g "Next" over and over. All the nodes end up being named Next.

**Comment by JadenBalogh** [comment]
@TheArchitect4855 Upon review, I think a major confusion factor here is that the Entry node has an Option text area but it's never actually used. This makes it seem like the user should enter the first opening message in that field. We should have special case labeling for the Entry node in particular, and hide the Option text area entirely there.
